config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: "home#index"

  get 'home/index'

  get 'terms' => 'pages#terms'
  get 'about' => 'pages#about'

  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  resources :articles do
    resources :comments, only: [:create]
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  validates :title, presence: true, length: { maximum: 140 }
  validates :text, presence: true, length: { maximum: 4000 }
  has_many :comments

  def subject
      title
  end

  def last_comment
    comments.last
  end
end

app/models/comment.rb
class Comment < ApplicationRecord
  validates :body, presence: true, length: { maximum: 4000 }
  belongs_to :article
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :email, presence: true
  validates :message, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :configure_permitted_parameters, if: :devise_controller?

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username]) 
  
    #devise_parameter_sanitizer.for(:sign_up) << :username

  end

end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  before_action :authenticate_user!, :only => [:new, :create, :edit]

  def index
    @articles = Article.all.order("created_at DESC")

  end

  def show
    @article = Article.find(params[:id])
  end

  def new

  end

  def create
    @article = Article.new(article_params)
    if @article.save
      redirect_to @article
    else
      render action: 'new'
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render action: 'edit'
    end

  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :text, :articleauthor)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  before_action :authenticate_user!, :only => [:create]

  def create
    @article = Article.find(params[:article_id])
    @article.comments.create(comment_params)

    redirect_to article_path(@article)
  end

  private

  def comment_params
    params.require(:comment).permit(:author, :body)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
    #@contact = Contact.new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

  private

  def contact_params
    params.require(:contact).permit(:email, :message)
  end
  
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    if params[:contact] != nil
    render plain: params[:contact].inspect
    end
  end

  def contacts
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

def terms

end

def about

end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/articles/edit.html.erb
<h1>Edit Article</h1>

<%= form_for :article, url: article_path(@article), method: :put do |f| %>
	<p>
		<%= f.label :title %><br />
		<%= f.text_field :title %>
	</p>

	<p>
		<%= f.label :text %><br />
		<%= f.text_area :text %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/articles/index.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<% @articles.each do |article| %>
				<h2><%= article.title %></h2>

				<p>
					<%= article.text %>
				</p>

				<p>
					<%= link_to 'Show', article_path(article) %>
					<% if user_signed_in? %>
						<% if current_user.username == article.articleauthor %>
							 | <%= link_to 'Edit', edit_article_path(article) %> |
							<%= link_to 'Destroy', article_path(article), method: :delete, data: { confirm: 'Are you sure?' } %>
						<% end %>
					<% end %>
				</p>

				<hr />
			<% end %>
		</div>
	</div>
</div>

app/views/articles/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1>New Article</h1>

				<%= form_for :article, url: articles_path do |f| %>
					<%= f.hidden_field :articleauthor, value: current_user.username %>

					<p>
						<%= f.label :title %><br />
						<%= f.text_field :title %>
					</p>

					<p>
						<%= f.label :text %><br />
						<%= f.text_area :text %>
					</p>

					<p>
						<%= f.submit %>
					</p>

				<% end %>

		</div>
	</div>
</div>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
	<%= @article.text %>
</p>

	<h2>Comments:</h2>

<% @article.comments.each do |comment| %>
	<p>
	<i><%= comment.author %> said:</i><br />
	</p>
	<p>
		<%= comment.body %>	
	</p>
	<hr />
<% end %>

<% if user_signed_in? %>
	<h2>Add comments:</h2>

<p>
<%= form_for([@article, @article.comments.build]) do |f| %>
	<p>
		Leave your comment here, <%= current_user.username %>:<br />
		<%= f.hidden_field :author, value: current_user.username %>
	</p>

	<p>
		<%= f.text_area :body %>
	</p>

	<p>
		<%= f.submit %>
	</p>
<% end %>
</p>
<% else %>
	<p> Please, <%= link_to 'Sign In', new_user_session_path %> to leave a comment.
	</p>
<% end %>

app/views/contacts/create.html.erb
<p>Thanks!</p>

app/views/contacts/new.html.erb
<div class="container">
	<div class="row">
		<div class="col-12">
			<h1><%= t('contacts.contact_us') %></h1>

			<%= form_for :contact, url: contacts_path do |f| %>
				<% if @contact && @contact.errors.any? %> 
					<p>
						<ul>
							<% @contact.errors.full_messages.each do |msg| %>
								<li><%= msg %></li>
							<% end %>
						</ul>
					</p>
				<% end %>

				<p>
					<%= f.label :email %><br />
					<%= f.text_field :email %>
				</p>

				<p>
					<%= f.label :message %><br />
					<%= f.text_area :message %>
				</p>

				<p>
					<%= f.submit 'Send Message' %>
				</p>

			<% end %>
		</div>
	</div>
</div>

app/views/home/contacts.html.erb
<h1>Contacts</h1>

<%= form_for :contact, url: "/home/index" do |f| %>
	<p>
		<%= f.label :email %><br />
		<%= f.text_field :email %>
	</p>

	<p>
		<%= f.label :message %><br />
		<%= f.text_area :message %>
	</p>

	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/home/index.html.erb
<div class="container">
	    <div class="row">
		    <div class="col-12">
				<h1><%= t('home.index_title') %></h1>
				<p><%= t('home.index_message') %></p>
		    </div>
		</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-12">
          <% if user_signed_in? %>

            <%= t('layout.layout_hello', username: current_user.username) %> | <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>

          <% else %>

            <%= link_to t('layout.layout_sign_in'), new_user_session_path %>

          <% end %>
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
          <%= yield %>
        </div>
      </div>
    </div>
    
    

  </body>
</html>

app/views/pages/about.html.erb
<h1>About us</h1>
<p>
It's all about us!
</p>

app/views/pages/terms.html.erb
<h1>Terms of service</h1>
<p>
	These are the terms of service!
</p>